### ISSUE TITLE
Suggestion: Adopting Hashicorp Terraform Provider Testing Framework

### ISSUE THREAD

**Issue by SebRosander** [vantage-sh/terraform-provider-vantage#25]
Hello team,

Hope you're all doing great! I've been diving into the terraform-provider-vantage project lately, and I must say, I like what you are building here. It's been a great experience contributing and watching the project evolve.

In working with the provider, I've encountered a few issues ([#17](https://github.com/vantage-sh/terraform-provider-vantage/issues/17), [#21](https://github.com/vantage-sh/terraform-provider-vantage/issues/21), [#23](https://github.com/vantage-sh/terraform-provider-vantage/issues/23), [#24](https://github.com/vantage-sh/terraform-provider-vantage/issues/24)) that led me to think about the long-term stability and reliability of our project.

I'd like to recommend prioritizing the implementation of automated and acceptance testing. HashiCorp provides a comprehensive [testing framework](https://developer.hashicorp.com/terraform/plugin/sdkv2/testing) specifically designed for Terraform providers, which could significantly enhance the reliability and quality of this project. Early adoption of such practices can prevent potential issues from becoming systemic, making future development smoother and more efficient.

Understanding that the project is in its early stages and resources may be limited, I'm more than willing to contribute to this effort. I believe that with collective collaboration, we can establish a solid testing foundation that ensures the provider's reliability and quality.

I'd love to hear your thoughts on this and discuss how we can collectively implement this moving forward.

**Comment by whereandy** [comment]
This is a great suggestion! I have also thought about this and think it is time to put this into practice. Have you set this up for other terraform providers? As we are resource constrained, one thing that would be helpful is if you could do this for a single resource, after which our team can have a look and apply the same testing across all the resources in the provider.

cc @macb @jaxxstorm

**Comment by SebRosander** [comment]
@whereandy - To reflect on our discussion offline. I've got some minor experience with the testing framework from previous work with other Terraform Providers. I've also built a small provider in-house that runs the testing framework. I'll do my best to find some time to implement a suggestion for a single resource and open a PR/Draft for it.

**Comment by whereandy** [comment]
@SebRosander thanks to https://github.com/vantage-sh/terraform-provider-vantage/pull/30, we have now started to use acceptance tests in our CI, and will continue to improve our coverage as time goes by.
