### ISSUE TITLE
[Feat] Import resource or add data source for a single Vantage folder

### ISSUE THREAD

**Issue by nmasur** [vantage-sh/terraform-provider-vantage#66]
Currently, the only Vantage data source to work with existing folders is [vantage_folders](https://registry.terraform.io/providers/vantage-sh/vantage/latest/docs/data-sources/folders). This seems to have the issue of not being able to select a specific folders; instead, you have to pull the data source and then loop through the list of folders to find the one you need by title.

On the other hand, we also can't bring an existing [vantage_folder](https://registry.terraform.io/providers/vantage-sh/vantage/latest/docs/resources/folder) into Terraform as a resource because it does not support imports.

This puts us in a bind when working with a folder added manually. We either have to search through a list from a data source or hardcode the folder token.

**Comment by brookemckim** [comment]
Thanks for the report @nmasur. Let me check with the team on this and get back to you.

**Comment by macb** [comment]
@nmasur `vantage_folder` and other resources now support `import` as of [v0.1.28](https://github.com/vantage-sh/terraform-provider-vantage/releases/tag/v0.1.28).
