### ISSUE TITLE
Bug: date_interval values defaulting to custom in cost report resource

### ISSUE THREAD

**Issue by DanielBrunoMatzui** [vantage-sh/terraform-provider-vantage#67]
We are encountering an issue with the Vantage Terraform provider where valid date_interval values such as "this_month", "last_30_days", and "last_3_months" are being changed to "custom" after terraform apply, resulting in a state inconsistency error. The issue occurs across multiple cost report configurations and according to the Vantage API SDK, these values should be valid without conversion. 

As a temporary workaround, we are setting all date_interval values to "custom", and then manually updating each cost report by clickopsing in the Vantage UI. 

This appears to be a bug in the provider that should be resolved to ensure predefined values function correctly.

![vantage_provider_inconsistent_date_interval_issue](https://github.com/user-attachments/assets/f2cdb1ed-0d44-4925-88c0-5ec334fe6330)

**Comment by brookemckim** [comment]
Hey @DanielBrunoMatzui thanks for reporting - will take a look at this.
