### ISSUE TITLE
Feature Request: Add Kubernetes Node Costs with Reserved Instances

### ISSUE THREAD

**Issue by DanielBrunoMatzui** [vantage-sh/terraform-provider-vantage#75]
Hi,

We’ve identified an issue with displaying costs for Kubernetes nodes covered by Reserved Instances in Azure. Currently, customers cannot view these costs in Vantage because the API being used, the CostDetailsReport API, pulls data from individual subscriptions and cannot integrate with the billing account scope due to CSP model limitations.

This issue appears to come from the indirect CSP model, where billing account data resides at the distributor's level (e.g., Tech Data) and is inaccessible at the customer level. Consequently, customers are unable to view or allocate Kubernetes Reserved Instance costs effectively.

Additional information:

- Commitments are made on the VMs hosting Kubernetes clusters, but Reserved Instance costs cannot be viewed or allocated between clusters or nodes.

- The amortized cost view does not reflect these costs, resulting in a significant gap in cost visibility.

Since integration at the billing account scope is not possible due to the CSP model, is there any workaround or alternative solution to resolve this limitation?

**Comment by brookemckim** [comment]
Hi Bruno, this is not related to the Terraform provider, but we have logged this on our side. Going to close this out.
